cancan configuration.
BC-MAY-21-ROR/kata-07-reloj-checador-team-01 pull request #33
Opened 2021-10-07 23:02 UTC by CUBOFIG

# Description
Cancan gem configuration and ability model.

This gem allows us to authorize users for Ruby on Rails, this configuration will allow us to restrict what resources a specific user can access.

 # Testing
It's correct installation can be seen in the Gemfile.

2021-10-08 02:05 UTC, YilKanda submitted a review, later dismissed
LGTM!

2021-10-08 17:40 UTC, jestradadeveloper approved these changes
LGTM

2021-10-08 18:08 UTC, JuanequeX approved these changes
LGTM

2021-10-08 19:48 UTC, EduardoGHdez commented on Gemfile
> +gem 'cancan'
```suggestion
gem 'cancancan' 
```

CanCan is no longer under mantainance, most of its community has migrated to use CanCanCan

From CanCan Documentation: 
> This project is abandoned, see its successor: CanCanCan


https://github.com/CanCanCommunity/cancancan

2021-10-08 19:49 UTC, EduardoGHdez requested changes

2021-10-08 19:49 UTC, EduardoGHdez commented on Gemfile
> +gem 'cancan'
```suggestion
gem 'cancancan' 
```

CanCan is no longer under mantainance, most of its community has migrated to use CanCanCan

From CanCan Documentation: 
> This project is abandoned, see its successor: CanCanCan


https://github.com/CanCanCommunity/cancancan

2021-10-08 21:06 UTC, JuanequeX approved these changes
LGTM

2021-10-08 22:58 UTC, YilKanda approved these changes
LGTM!

2021-10-08 23:25 UTC, merged

2021-10-11 16:37 UTC, EduardoGHdez commented
You're welcome 👋🏽