Add react to project
BC-MAY-21-ROR/kata-07-reloj-checador-team-01 pull request #7
Opened 2021-09-27 23:16 UTC by adrianMRJ

## What does this change?

Add react functionality to our project.

## Why are you changing that?

Because the project need the react model to code in front-end.

## How do you manually test this?

You can run the index view and it should deploy a greeting.

## Merge/Deploy Checklist
* [x]   It has been reviewed and accepted.

2021-09-27 23:25 UTC, jclopezdev reviewed
What do you need the pli file for?

2021-09-28 00:30 UTC, adrianMRJ commented on app/controllers/static_controller.rb
> +end
Solved

2021-09-28 00:34 UTC, adrianMRJ commented on Gemfile
> +# Use Puma as the app servers
It's not really necessary, solved

2021-09-28 00:38 UTC, YilKanda requested changes

2021-09-28 00:38 UTC, YilKanda commented on app/controllers/v1/things_controller.rb
> +end
Yes, you can solve it manually.

2021-09-28 00:39 UTC, adrianMRJ commented on app/controllers/v1/things_controller.rb
> +end
Ok, it's solved

2021-09-28 00:49 UTC, YilKanda approved these changes
LGTM!

2021-09-28 12:41 UTC, YilKanda approved these changes
LGTM!

2021-09-28 20:23 UTC, merged